version: '3.5'

#services:
#  backend:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "5000:80"
#    depends_on:
#      - postgres_db #Until postgres starts, our service will not start
#    networks:
#      - myAppNetwork

#  client:
#    ports:
#      - "5001:3000"

#  postgres_db:
#    container_name: postgres_container
#    image: postgres:16
#    environment:
#      POSTGRES_USER: azure_admin
#      POSTGRES_PASSWORD: Hgfpbp31
#      POSTGRES_DB: temp-db1
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    networks:
#      - myAppNetwork
#volumes:
#  postgres-data:



  # d:/ExamShop/WebApi/
#version: '3.4'

#services:
#  webapi:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=https://+:443;http://+:80
#    ports:
#      - "80"
#      - "443"
#    volumes:
#      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
#      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro