version: '3.9'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
  client:
    ports:
      - "5001:3006"

  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx.conf
    ports:
      - "80:80"